/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eddpractica1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author Rodolfo
 */
public class CrearZombies extends javax.swing.JFrame {

    public static ListaZombie zombies;
    public ListaPlanta plantas;
    public Lista_Jugador jugadores;
    public JChomboBox jchombobox;
    int cantZombies;
    /**
     * Creates new form CrearZombies
     */
    /**
     * Array Imagenes de Zombies
     */
    public ImageIcon[] ItemsZombies = {
        new ImageIcon(getClass().getResource("/Images/zombie1.png")),
        new ImageIcon(getClass().getResource("/Images/zombie2.png")),
        new ImageIcon(getClass().getResource("/Images/zombie3.png")),
        new ImageIcon(getClass().getResource("/Images/zombie4.png")),
        new ImageIcon(getClass().getResource("/Images/zombie5.png")),
        new ImageIcon(getClass().getResource("/Images/zombie6.png")),
        new ImageIcon(getClass().getResource("/Images/zombie7.png"))
    };

    public CrearZombies() {
        initComponents();
        jchombobox = new JChomboBox(ItemsZombies.length);
        jComboRender render = new jComboRender(ItemsZombies);
        jchombobox.setRenderer(render);

        PanelCombo.add(jchombobox);
        
        jchombobox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                System.out.println("Se Selecciono la Imagen " + jchombobox.getSelectedItem());
            }
        });
        
        cantZombies = JugZombies.cantidad;
        ContZom.setText("Cantidad de Zombies: "+Integer.toString(cantZombies));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btbAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        ComboDisparo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPtsAtaque = new javax.swing.JTextField();
        txtPtsDefensa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btbModificar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        PanelCombo = new javax.swing.JPanel();
        ContZom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SketchFlow Print", 2, 12)); // NOI18N
        jLabel1.setText("Imagen");

        jLabel4.setFont(new java.awt.Font("SketchFlow Print", 2, 12)); // NOI18N
        jLabel4.setText("Puntos Defensa");

        btbAdd.setText("Agregar");
        btbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        ComboDisparo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disparo", "Directo" }));

        jLabel5.setFont(new java.awt.Font("SketchFlow Print", 2, 12)); // NOI18N
        jLabel5.setText("Ataque");

        jLabel3.setFont(new java.awt.Font("SketchFlow Print", 2, 12)); // NOI18N
        jLabel3.setText("Puntos Ataque");

        jLabel2.setFont(new java.awt.Font("SketchFlow Print", 2, 12)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel6.setFont(new java.awt.Font("SimSun-ExtB", 0, 24)); // NOI18N
        jLabel6.setText("Creacion de Zombies");

        btbModificar.setText("Modificar");

        btnSiguiente.setText("Siguiente>>");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelComboLayout = new javax.swing.GroupLayout(PanelCombo);
        PanelCombo.setLayout(PanelComboLayout);
        PanelComboLayout.setHorizontalGroup(
            PanelComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        PanelComboLayout.setVerticalGroup(
            PanelComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        ContZom.setText("Zombies  Restantes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btbAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btbModificar)
                        .addGap(100, 100, 100)
                        .addComponent(btnSiguiente))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(PanelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPtsAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPtsDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboDisparo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(ContZom, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(ContZom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(PanelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboDisparo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPtsAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPtsDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btbAdd)
                    .addComponent(btnSiguiente)
                    .addComponent(btbModificar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbAddActionPerformed
        String nombre, ataque;
        int ptsAtaque, ptsDefensa;
        int imagen = (int)jchombobox.getSelectedItem();
        String url = getImagen2(imagen);        
        
        nombre = txtNombre.getText();
        ataque = (String) ComboDisparo.getSelectedItem();
        ptsAtaque = Integer.parseInt(txtPtsAtaque.getText());
        ptsDefensa = Integer.parseInt(txtPtsDefensa.getText());
        
        System.out.println("imagen"+imagen);

        Zombie p = new Zombie(nombre, ataque, url, ptsDefensa, ptsAtaque);
        if (zombies == null) {
            zombies = new ListaZombie(p);
        } else {
            zombies.add(p);
        }
        
        cantZombies-=1;
        ContZom.setText("Cantidad de Plantas: "+Integer.toString(cantZombies));
        ContZom.repaint();
        
        if(cantZombies == 0){
            btbAdd.setEnabled(false);
        }
        zombies.recorre();

    }//GEN-LAST:event_btbAddActionPerformed
    
    public String getImagen2(int op){
        String url="";
        switch(op){
            case 0:
                url = "/Images/zombie1.png";
            case 1:
                url = "/Images/zombie2.png";
            case 2:
                url = "/Images/zombie3.png";
            case 3:
                url = "/Images/zombie4.png";
            case 4:
                url =  "/Images/zombie5.png";
            case 5:
                url = "/Images/zombie6.png";
            case 6:
                url = "/Images/zombie7.png";
        }
        return url;
    }
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String nombre = JOptionPane.showInputDialog("Ingrese Nombre a Borrar");
        zombies.delete(nombre);
        System.out.println("Se borro" + zombies.buscarDato(nombre));
        
        cantZombies+=1;
        ContZom.setText("Cantidad de Zombies: "+Integer.toString(cantZombies));
        ContZom.repaint();
        
        if(cantZombies != 0){
            btbAdd.setEnabled(false);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if (zombies != null) {
            Juego jp = new Juego();
            jp.plantas = plantas;
            jp.zombies = zombies;
            this.dispose();
            jp.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Ingrese una Planta");
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearZombies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearZombies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearZombies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearZombies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearZombies().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboDisparo;
    private javax.swing.JLabel ContZom;
    private javax.swing.JPanel PanelCombo;
    private javax.swing.JButton btbAdd;
    private javax.swing.JButton btbModificar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPtsAtaque;
    private javax.swing.JTextField txtPtsDefensa;
    // End of variables declaration//GEN-END:variables
}
